### ISSUE TITLE
[BP] X-Payment-Discord-Merchant

### ISSUE THREAD

**Issue by AnimusXCASH** [X-CASH-official/builders-program#5]
# BP Proposition 🏗

### Type

- [ ] **Request For Contribution (RFC):**  
- [X] **Request For Funding (RFF)**  

### Description
Merchant system built on X-Payment will allow Discord Users to monetize perks/roles on their communities and built economy system however they see fit. 

There are numerous communities which offer payed services for their members. The process of "money" collection and perk management however takes a lot of time from them. For Discord servers in size already over 50 members this brings time constraints and management issues. While they need to develop content which they are selling, they are required as well to monitor payments upon purchases, manage perks (assigning and removing), and numerous other tasks in order to be successful.

Objective of the Merchant Service is to remove the "need for time" and "lost nerves" and let owners and other creative staff focus on content production rather than on micro tasks. 

Basic idea...
With Merchant integrated into X-Payment, owner would be able to create/monetize perk through setup process. He would be required to specify the time limit (time-bomb) and value of the perk.  Once successfully completed, perk would become up for grabs from the server members. 
When user purchases it, system would deduct the required Perk value set in XCASH from the user's X-Payment wallet and transfer the amount to the Server's wallet where access is granted only to the community owner. System would than further assign the purchased perk to the user. Once the time assigned to the perk expires, system would automatically remove the perk from the user, stripping him off all the access and rights assigned to the purchased perk by owner.

This might be as well one of the parts of the X-Payment system allowing us to spread the word on X-CASH and expand X-Payment and knowledge on X-Cash to other communities. 

### Prerequisites
required skills and knowledge area are: python syntax and relevant core and 3rd party integrated libraries, understanding of  X-Payment blueprint and how it  operates, XCASH chain characteristics and RPC commands, MongoDB queries and role in the X-Payments system. 

### Milestones / Deliverables
- Fully functional merchant system with the commands dedicated to Discord server owner and for the members. 
- Backend supporting the goal of the Time-bomb
### Additional information / Budgeting
- Up to discussion

**Comment by zachhildreth** [comment]
Hi @AnimusXCASH 
This sounds good to me, and seems needed for x-payments.

We can do 500 USD in xcash for this once its complete and merged to github and deployed on our server

Let me know if this sounds good to you.

**Comment by AnimusXCASH** [comment]
Accepted

**Comment by zachhildreth** [comment]
great, looking forward to this!

**Comment by AnimusXCASH** [comment]
✅

**Comment by zachhildreth** [comment]
Hi @AnimusXCASH It looks great and is deployed!
Please leave an XCA address so we can send payment

**Comment by AnimusXCASH** [comment]
XCA1d9H82oZP1ytt8ULMVFa6GNaX1RWHz8EFpwFNDgDbCEkzvZGP384Qfz6DJxjsmU2ernSQguqKgLDVkm1VteVT4ZiPJiSEVN

**Comment by zachhildreth** [comment]
Hi @AnimusXCASH the payment has been sent in a public tx
here are the details

```
 Amount (USD): 500
 Amount (XCASH): 4920635
 Transaction Hash: e83922afd9f5f8c262134e2871accc127e23e925b44bcf574fbdac150c9cb739

```
